function UpdateTable() {
	var arr = [];
	while(arr.length < 10){
		var randomnumber = Math.floor(Math.random()*10);
		if(arr.indexOf(randomnumber) > -1 ) continue;
		arr[arr.length] = randomnumber;
	}

	tmp1 = 'cell' + 1;
	tmp2 = 'cell' + 2;
	tmp3 = 'cell' + 3;
	tmp4 = 'cell' + 4;
	tmp5 = 'cell' + 5;
	tmp6 = 'cell' + 6;
	tmp7 = 'cell' + 7;
	tmp8 = 'cell' + 8;
	tmp9 = 'cell' + 9;

	var temp = [tmp1, tmp2, tmp3, tmp4, tmp5, tmp6, tmp7, tmp8, tmp9];

	for (var i = 0; i < 10; i++) {
		document.getElementById(temp[i]).innerHTML = arr[i];
	}	
} 


UpdateTable();
